# Generated by Django 5.0.1 on 2025-10-09 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date_poster",
            new_name="date_posted",
        ),
    ]
